### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by iwanikhalid** [iwanikhalid/tapak#19]
We have 3 slideshows
- Homepage
- Food Truck Profile
- Tapak Profile

Generally
- Slideshows can have unlimited slides of any type: video or image with or without caption
- Video will play in full width and with sound....  I know previously I said without sound for homepage but I think it's weird without sound now. I hope we can revert. Eeek, sorry.
- When the cursor is on the slide, the slide won't move to the next.

**Bugs / Not yet installed stuffs I found regarding Slideshows**
- [x] Homepage > Video is playing without sound. Let's turn it on again
- [x] Homepage > Video is playing but the slideshow is still sliding to the next slides - this shouldn't happen
- [x] ~~Homepage > Can we have Welcome to Tapak on a video slide too? Or it would be just weird? Haha~~

- [x] Tapak Profile > we don't have Slideshow on WP Admin and website yet

- [x] FT Profile > We haven't added image slide on the website yet
- [x] FT Profile > Need to allow unlimited slides addition
- [x] FT Profile > Love the video slide. Let's just make it play full-width

**Comment by aienzaini** [comment]
If you want to create unlimited slideshow for Tapak/FT, you should do it via Slideshow. Select the Tapak/FT when creating the slideshow AND please leave the youtube url and image intro empty in Tapak/FT. The priority of showing Slideshow is as follows:

1. Tapak/FT > Intro (Youtube video URL)
2. Tapak/FT > Intro (image)
3. Tapak/FT > Slideshow (tagged with Tapak/FT).

I don't agree with having the Walcome to Tapak on video slide. We should put it into the video so that they have more control in future.

**Comment by iwanikhalid** [comment]
Ok noted and agreed @aienzaini !

**Comment by iwanikhalid** [comment]
For keeps

**TAPAK LOGO ON SLIDESHOW**

```<img class="aligncenter size-full wp-image-14" src="http://52.163.95.207/tapak/wp-content/uploads/2016/06/tapak-slideshow1-content.png" alt="tapak-slideshow1-content" width="162" height="198" />
```

**TAPAK LOGO WITH CAPTION ON SLIDESHOW**

```<img class="aligncenter size-full wp-image-14" src="http://52.163.95.207/tapak/wp-content/uploads/2016/06/tapak-slideshow1-content.png" alt="tapak-slideshow1-content" width="162" height="198" />
<p style="text-align: center;">The new food truck haven. In the heart of Kuala Lumpur.</p>
<p style="text-align: center;"><a href="http://52.163.95.207/tapak/about-us/"><span class="button">VIEW OUR STORY</span></a></p>
```
